/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuppetRouteImport } from './routes/puppet'
import { Route as TranscriptRouteImport } from './routes/transcript'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuppetRoute = PuppetRouteImport.update({
  id: '/puppet',
  path: '/puppet',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptRoute = TranscriptRouteImport.update({
  id: '/transcript',
  path: '/transcript',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/puppet': typeof PuppetRoute
  '/transcript': typeof TranscriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/puppet': typeof PuppetRoute
  '/transcript': typeof TranscriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/puppet': typeof PuppetRoute
  '/transcript': typeof TranscriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/puppet' | '/transcript'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/puppet' | '/transcript'
  id: '__root__' | '/' | '/puppet' | '/transcript'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PuppetRoute: typeof PuppetRoute
  TranscriptRoute: typeof TranscriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puppet': {
      id: '/puppet'
      path: '/puppet'
      fullPath: '/puppet'
      preLoaderRoute: typeof PuppetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcript': {
      id: '/transcript'
      path: '/transcript'
      fullPath: '/transcript'
      preLoaderRoute: typeof TranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PuppetRoute: PuppetRoute,
  TranscriptRoute: TranscriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
