/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as PuppetRouteImport } from './routes/puppet'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StarmapRouteImport } from './routes/starmap'
import { Route as TranscriptRouteImport } from './routes/transcript'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const PuppetRoute = PuppetRouteImport.update({
  id: '/puppet',
  path: '/puppet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StarmapRoute = StarmapRouteImport.update({
  id: '/starmap',
  path: '/starmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptRoute = TranscriptRouteImport.update({
  id: '/transcript',
  path: '/transcript',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/costs': typeof CostsRoute
  '/dashboard': typeof DashboardRoute
  '/heatmap': typeof HeatmapRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/puppet': typeof PuppetRoute
  '/settings': typeof SettingsRoute
  '/starmap': typeof StarmapRoute
  '/transcript': typeof TranscriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/costs': typeof CostsRoute
  '/dashboard': typeof DashboardRoute
  '/heatmap': typeof HeatmapRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/puppet': typeof PuppetRoute
  '/settings': typeof SettingsRoute
  '/starmap': typeof StarmapRoute
  '/transcript': typeof TranscriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/costs': typeof CostsRoute
  '/dashboard': typeof DashboardRoute
  '/heatmap': typeof HeatmapRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/puppet': typeof PuppetRoute
  '/settings': typeof SettingsRoute
  '/starmap': typeof StarmapRoute
  '/transcript': typeof TranscriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/costs'
    | '/dashboard'
    | '/heatmap'
    | '/leaderboards'
    | '/puppet'
    | '/settings'
    | '/starmap'
    | '/transcript'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/costs'
    | '/dashboard'
    | '/heatmap'
    | '/leaderboards'
    | '/puppet'
    | '/settings'
    | '/starmap'
    | '/transcript'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/costs'
    | '/dashboard'
    | '/heatmap'
    | '/leaderboards'
    | '/puppet'
    | '/settings'
    | '/starmap'
    | '/transcript'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CostsRoute: typeof CostsRoute
  DashboardRoute: typeof DashboardRoute
  HeatmapRoute: typeof HeatmapRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  PuppetRoute: typeof PuppetRoute
  SettingsRoute: typeof SettingsRoute
  StarmapRoute: typeof StarmapRoute
  TranscriptRoute: typeof TranscriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puppet': {
      id: '/puppet'
      path: '/puppet'
      fullPath: '/puppet'
      preLoaderRoute: typeof PuppetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starmap': {
      id: '/starmap'
      path: '/starmap'
      fullPath: '/starmap'
      preLoaderRoute: typeof StarmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcript': {
      id: '/transcript'
      path: '/transcript'
      fullPath: '/transcript'
      preLoaderRoute: typeof TranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CostsRoute: CostsRoute,
  DashboardRoute: DashboardRoute,
  HeatmapRoute: HeatmapRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  PuppetRoute: PuppetRoute,
  SettingsRoute: SettingsRoute,
  StarmapRoute: StarmapRoute,
  TranscriptRoute: TranscriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
